config/routes.rb
Rails.application.routes.draw do
  get 'report' => 'transactionlogger#report'

  get 'session/homepage'
  post 'create_account' => 'session#new'
  
  post 'login' => 'session#login'
  delete 'logout' => 'session#logout'

  resources :loans

  root 'session#homepage'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  load 'logging.rb'
  
  belongs_to :user
  before_update :logchange
  before_save :roundamount
  
  def roundamount
    self.amount.round(2)
  end
  
  def logchange
    logall(self.user_id)
  end

end

app/models/transactionlogger.rb
class Transactionlogger < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
#VALID_PHRASE = /\A[a-zA-Z0-9\s]+\Z/i #/\A[\sa-z0-9]+\Z/i

validates :name, presence: true, uniqueness: true#, format: { with: VALID_PHRASE }
validates :password, presence: true, length: { minimum: 8 } 
  #what gets sent to the database is an encrypted version so SQL injection is not an issue with this 

has_secure_password
has_many :loans

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
include SessionHelper

private
  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_url # halts request cycle
    end
  end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /loans
  # GET /loans.json
  def index
    @loans = current_user.loans
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    
    @loan = current_user.loans.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:amount, :enddate)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def homepage
  end
  
  def login
    user = User.find_by(name: params[:user][:name])
    
    if user && user.authenticate(params[:user][:password]) then
      log_in(user)
      redirect_to loans_path
    else
      redirect_to root_path, notice: "Invalid name / password combination"
    end
  end
  
  def logout
    log_out
    redirect_to root_url
  end
  
  def new
    User.create(name: params[:user][:name], password: params[:user][:password])
    login
  end
end

app/controllers/transactionlogger_controller.rb
class TransactionloggerController < ApplicationController
  def report
    
    loans = []
    if params[:q] && params[:q][:key] then
      
      key = params[:q][:key]
        
         #eliminating the record id from the key if not only looking at repeated edits of the same record
      loans = Transactionlogger.where(key: key)
      

      if params[:q][:date_gt].present? then
        loans = loans.where("created_at > ?", params[:q][:date_gt].to_datetime)
      end
      if params[:q][:date_lt].present? then
        loans = loans.where("created_at < ?", params[:q][:date_lt].to_datetime)
      end

      if params[:q][:count] then
        threshold = params[:q][:count].to_i
        @flagged = []
        (params[:q][:same].present? && params[:q][:same] == 1) ? grouped = loans.group("user", "recordid") : grouped = loans.group("user")
        
        grouped.count.each do |key, value|
          if value > threshold then
            @flagged.push({user: key, num_events: value})
          end
        end
      else
        @flagged = loans.group("user")
      end
    else
      @flagged = []      
    end
    for flag in @flagged
        flag[:email] = User.find(flag[:user].to_i).name
        flag[:user] = nil
    end
  end

  def alltime
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    reset_session
    session[:user_id] = user.id #Creates a cookie that expires with the session, storing the user ID
  end
  def log_out
    reset_session
    @current_user = nil
  end
  def current_user
    if session[:user_id].nil? then 
      return
    end
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/transactionlogger_helper.rb
module TransactionloggerHelper
  
end

app/views/layouts/_header.html.erb
  <div class="container">
  	<% if current_user.present? %>
  		<div align = "right">
      		<ul> <%= link_to "Log out", logout_path, method: "delete" %> </ul>
      	</div>
      	<%= link_to :reports, report_path %>
      	<%= link_to :loans, loans_path %>
    	<hr>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @pagetitle.present? ? @pagetitle : 'Logging test'%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Amount $" %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label "Payback Date" %><br>
    <%= f.date_field :enddate %>
  </div>
  <div class="actions">
    <%= f.submit "Register loan"%>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Loans</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Enddate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.amount %></td>
        <td><%= loan.enddate %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @loan.amount %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @loan.enddate %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>

app/views/session/homepage.html.erb
<h1>Log in / New Account</h1>


<div class="col-md-6 col-md-offset-3">
  	
		<%= form_for(:user, url: login_path) do |f| %>
		<div class="row">
	
		  <%= f.label :email %>
		  <%= f.email_field :name, class: 'form-control' %>
		
		  <%= f.label :password %>
		  <%= f.password_field :password, class: 'form-control' %>
		
		</div>
		  <%= f.submit "Log in", class: "btn btn-primary" %>
		<% end %>
	
</div>
<hr>
<div class="col-md-6 col-md-offset-3">
    <p><h4>New user?</h4></p>
    <%= form_for(:user, url: create_account_path) do |f| %>

  	<div class="row">
      <%= f.label :email %>
      <%= f.email_field :name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

  	</div>
      <%= f.submit "New Account", class: "btn btn-primary" %>
    <% end %>
    
</div>

app/views/transactionlogger/month.html.erb
<h1>Transactionlogger#month</h1>
<p>Find me in app/views/transactionlogger/month.html.erb</p>

app/views/transactionlogger/report.html.erb
<h1>Reports</h1>

<h3><%= params[:q].nil? ? "Please Enter Search Parameters" : nil %></h3>

<%= form_for :q, url: report_path, method: :get  do |f| %>

  <div class="field">
    <%= f.label "Type of Change" %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label "By individual loan?" %><br>
    <%= f.check_box :same %>
  </div>

  <div class="field">
    <%= f.label "After" %><br>
    <%= f.date_field :date_gt %>
  </div>
  <div class="field">
    <%= f.label "Before" %><br>
    <%= f.date_field :date_lt %>
  </div>
  <div class="field">
    <%= f.label "More than" %><br>
    <%= f.number_field :count %><br>
    <%= f.label "changs made" %>
  </div>
  <div class="actions">
    <%= f.submit "Search" %>
  </div>

  <% if @flagged.length > 0 then %>
  	<table>
  		<tr>
  			<th>User Email</th>
  			<th>Number of Changes</th>
  		</tr>
	  	<% for user in @flagged do %>
	  	<tr>
	  		<td><%= user[:email] %></td>
	  		<td><%= user[:num_events] %></td>
	  	</tr>
	  	
	  	
	  	<% end %>
	</table>
  <% end %>

<% end %>